[package]
name = "rustGraphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix-web = "4"
mongodb = "2.3.1"
tokio = "1.22.0"
serde = { version = "1.0.126", features = ["derive"] }
